version: 2
<<<<<<< HEAD
build:
  os: ubuntu-22.04

  tools:
    python: "3.11"

  apt_packages:
    - libpango1.0-dev

=======
formats: all
conda:
  environment: docs/environment.yml
>>>>>>> upstream/main
python:
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .

sphinx:
  configuration: docs/conf.py

formats: all
